function IdSwxT=IdSATURxT(Tgau,Tsol,Tliq,Sres,Rsat,Wpar,Mpar)
switch Rsat
    case 1
        if Tgau<=Tsol
            IdSwxT=0.0;
        elseif Tgau<Tliq && Tgau>Tsol
            IdSwxT_0=- Tsol*exp(-(Tliq - Tsol)^2/Wpar^2)*(Sres - 1) + ...
                (pi^(1/2)*erf((Tliq - Tsol)*(-1/Wpar^2)^(1/2)*1i)*...
                (Sres - 1)*1i)/(2*(-1/Wpar^2)^(1/2));
            IdSwxT=- Tgau*exp(-(Tgau - Tliq)^2/Wpar^2)*(Sres - 1) - ...
                (pi^(1/2)*erf((Tgau - Tliq)*(-1/Wpar^2)^(1/2)*1i)*...
                (Sres - 1)*1i)/(2*(-1/Wpar^2)^(1/2))-IdSwxT_0;
        else
            IdSwxT_0p=- Tsol*exp(-(Tliq - Tsol)^2/Wpar^2)*(Sres - 1) + ...
                (pi^(1/2)*erf((Tliq - Tsol)*(-1/Wpar^2)^(1/2)*1i)*...
                (Sres - 1)*1i)/(2*(-1/Wpar^2)^(1/2));
            IdSwxT_0=- Tgau*exp(-(Tgau - Tliq)^2/Wpar^2)*(Sres - 1) - ...
                (pi^(1/2)*erf((Tgau - Tliq)*(-1/Wpar^2)^(1/2)*1i)*...
                (Sres - 1)*1i)/(2*(-1/Wpar^2)^(1/2)) -IdSwxT_0p ;
            IdSwxT=IdSwxT_0;
        end
    case 0
        Btem=(Sres-1)/Mpar;
        if Tgau>=Btem
            IdSwxT_0=Mpar*Btem^2/2;
            IdSwxT=Mpar*Tgau^2/2-IdSwxT_0;
            if Tgau>Tliq
                IdSwxT_0p=Mpar*Btem^2/2;
                IdSwxT_0=Mpar*Tliq^2/2-IdSwxT_0p;
                IdSwxT=IdSwxT_0;
            end
        else
            IdSwxT=0.0;
        end
    case 2
        if Tgau<=Tsol
            IdSwxT=0.0;
        elseif Tgau<Tliq && Tgau>Tsol
            IdSwxT_0= -((cos((pi*(Tliq/2 - Tsol/2))/(Tliq - ...
                Tsol))*(Tliq - Tsol)^2*(Sres - 1))/pi -...
                Tsol*sin((pi*(Tliq/2 - Tsol/2))/(Tliq -...
                Tsol))*(Tliq - Tsol)*(Sres - 1))/(2*Tliq - 2*Tsol);
            IdSwxT=(Tgau*sin((pi*(Tliq/2 - Tgau + Tsol/2))/(Tliq -...
                Tsol))*(Tliq - Tsol)*(Sres - 1) -...
                (cos((pi*(Tliq/2 - Tgau + Tsol/2))/(Tliq -...
                Tsol))*(Tliq - Tsol)^2*(Sres - 1))/pi)/(2*Tliq - 2*Tsol)-IdSwxT_0;
        else
            IdSwxT_0p= -((cos((pi*(Tliq/2 - Tsol/2))/(Tliq - ...
                Tsol))*(Tliq - Tsol)^2*(Sres - 1))/pi -...
                Tsol*sin((pi*(Tliq/2 - Tsol/2))/(Tliq -...
                Tsol))*(Tliq - Tsol)*(Sres - 1))/(2*Tliq - 2*Tsol);
            IdSwxT_0=-((cos((pi*(Tliq/2 - Tsol/2))/(Tliq - ...
                Tsol))*(Tliq - Tsol)^2*(Sres - 1))/pi + ...
                Tliq*sin((pi*(Tliq/2 - Tsol/2))/(Tliq -...
                Tsol))*(Tliq - Tsol)*(Sres - 1))/(2*Tliq - 2*Tsol)-IdSwxT_0p;
            IdSwxT=IdSwxT_0;
        end
end
end